/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
#ifndef _UAPI_ASM_ALPHA_PERF_REGS_H
#define _UAPI_ASM_ALPHA_PERF_REGS_H

enum perf_event_alpha_regs {
	PERF_REG_ALPHA_R0,
	PERF_REG_ALPHA_R1,
	PERF_REG_ALPHA_R2,
	PERF_REG_ALPHA_R3,
	PERF_REG_ALPHA_R4,
	PERF_REG_ALPHA_R5,
	PERF_REG_ALPHA_R6,
	PERF_REG_ALPHA_R7,
	PERF_REG_ALPHA_R8,
	PERF_REG_ALPHA_R16,
	PERF_REG_ALPHA_R17,
	PERF_REG_ALPHA_R18,
	PERF_REG_ALPHA_R19,
	PERF_REG_ALPHA_R20,
	PERF_REG_ALPHA_R21,
	PERF_REG_ALPHA_R22,
	PERF_REG_ALPHA_R23,
	PERF_REG_ALPHA_R24,
	PERF_REG_ALPHA_R25,
	PERF_REG_ALPHA_R26,
	PERF_REG_ALPHA_R27,
	PERF_REG_ALPHA_R28,
	PERF_REG_ALPHA_GP,
	PERF_REG_ALPHA_PC,
	PERF_REG_ALPHA_PS,
	PERF_REG_ALPHA_MAX,
};

#endif /* _UAPI_ASM_ALPHA_PERF_REGS_H */
